from pathlib import Path

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.core.config import get_settings
from app.models.prediction import Prediction
from app.models.report import Report, ReportStatus
from app.models.user import User
from app.services.audit import create_audit_log

settings = get_settings()


async def generate_report(db: AsyncSession, prediction_id: str, actor: User) -> Report:
    prediction = await db.scalar(
        select(Prediction)
        .where(Prediction.id == prediction_id)
        .options(
            selectinload(Prediction.patient),
            selectinload(Prediction.microbe),
            selectinload(Prediction.antibiotic),
        )
    )
    if prediction is None:
        raise ValueError('Prediction not found')

    settings.report_storage_dir.mkdir(parents=True, exist_ok=True)
    output_path = settings.report_storage_dir / f'{prediction.id}.pdf'
    pdf = canvas.Canvas(str(output_path), pagesize=letter)
    pdf.setTitle('AMR Clinical Decision Support Report')
    pdf.drawString(72, 760, 'AMR Clinical Decision Support Report')
    pdf.drawString(72, 735, f'Prediction ID: {prediction.id}')
    pdf.drawString(72, 715, f'Microbe: {prediction.microbe.name if prediction.microbe else prediction.microbe_id}')
    pdf.drawString(72, 695, f'Antibiotic: {prediction.antibiotic.name if prediction.antibiotic else prediction.antibiotic_id}')
    pdf.drawString(72, 675, f'Result: {prediction.prediction_label.value.title()}')
    pdf.drawString(72, 655, f'Resistant probability: {prediction.resistant_probability:.2%}')
    pdf.drawString(72, 635, f'Confidence score: {prediction.confidence_score:.2%}')
    pdf.drawString(72, 615, 'Clinical insight:')
    text_object = pdf.beginText(72, 595)
    for line in prediction.explanation_text[:350].split('. '):
        text_object.textLine(line.strip())
    pdf.drawText(text_object)
    pdf.drawString(72, 500, f'Alternatives: {", ".join(prediction.recommended_alternatives) or "None available"}')
    pdf.drawString(72, 480, 'Generated by AMR Intelligence Platform')
    pdf.save()

    report = Report(
        prediction_id=prediction.id,
        created_by_id=actor.id,
        file_path=str(output_path.relative_to(settings.project_root)),
        status=ReportStatus.GENERATED,
    )
    db.add(report)
    await db.flush()
    await create_audit_log(db, 'report.generated', 'report', report.id, actor.id, {'prediction_id': prediction.id})
    await db.commit()
    await db.refresh(report)
    return report
